
modLoader="javafml" #mandatory


loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.


license="MIT License"


[[mods]] #mandatory

modId="so_many_enchants" #mandatory

version="${file.jarVersion}" #mandatory

displayName="So Many Enchants!!!" #mandatory

issueTrackerURL="https://github.com/YeetmanLord/So-Many-Enchants/issues"

displayURL="https://www.curseforge.com/minecraft/mc-mods/enchants"

logoFile="icon.png" #optional


credits="Forge for creating the resources to code this mod" #optional

authors="YeetManLord" #optional

description='''
Adds a wide variety of new enchantments to 
the game.

Yay finally in full release!
'''

[[dependencies.so_many_enchants]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.so_many_enchants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
